# Use Node.js 20 on Alpine Linux as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 5173 (assuming your application listens on this port)
EXPOSE 5173

# Command to run the application
CMD ["npm","run", "dev-exposed"]
