version: "3.8"

services:
  frontend:
    image: frontend_course_platform
    stdin_open: true
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_cp
    restart: always
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
