# Use Node.js 20 on Alpine Linux as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Install Redis
# RUN apk add --no-cache redis

# Copy the Prisma directory
COPY prisma ./prisma

# Copy the rest of the application code
COPY . .


# Build the TypeScript files
# RUN npm run build

# Expose port 3000 (assuming your application listens on this port)
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev:docker"]
