version: "3.8"

services:
  backend:
    image: backend_course_platform
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_cp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://happy:happy123@db:5432/mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:9.6
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: happy
      POSTGRES_PASSWORD: happy123
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_volume:
  redis_volume:
